name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "build/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Tools
        run: |
          sudo apt-get -q -y update &&
          sudo apt-get -q -y install fpga-icestorm iverilog nextpnr-ice40 yosys yosys-abc;

      - name: Test and Synthesise
        run: |
          cd "${GITHUB_WORKSPACE}" && \
          build/test.sh && \
          build/verify.sh && \
          build/synthesise.sh;

      - uses: actions/upload-artifact@v6
        with:
          name: piclike-out
          path: |
            {{github.workspace}}/out/tests/passed
            {{github.workspace}}/out/tests/failed
            {{github.workspace}}/out/proofs/passed
            {{github.workspace}}/out/proofs/failed
            {{github.workspace}}/out/synthesised
