name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/**"
      - "src/**"
      - "build/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Tools
        run: |
          sudo apt-get -q -y update &&
          sudo apt-get -q -y install fpga-icestorm iverilog nextpnr-ice40 yosys yosys-abc &&
          npm install -g --ignore-scripts wavedrom;

      - name: Test and Synthesise
        run: |
          cd "${GITHUB_WORKSPACE}/build" && \
          ./test.sh && \
          ./verify.sh && \
          ./synthesise.sh;

      - uses: actions/upload-artifact@v6
        with:
          name: piclike-out
          if-no-files-found: error
          path: |
            ${{github.workspace}}/build/out/tests/passed
            ${{github.workspace}}/build/out/tests/failed
            ${{github.workspace}}/build/out/proofs/passed
            ${{github.workspace}}/build/out/proofs/failed
            ${{github.workspace}}/build/out/synthesis
